ragbv2/frontend/frontend/urls.py
from django.urls import path

from .views import HomeView, LightView, TokenView

app_name = "frontend"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("light/<str:light>/", LightView.as_view()),
    path("token", TokenView.as_view()),
]

ragbv2/frontend/ragb/urls.py
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("authens/", include("authens.urls")),
    path("", include("frontend.urls")),
]

if settings.ENABLE_DJDT:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

ragbv2/frontend/frontend/models.py
from django.db import models

# Create your models here.

ragbv2/frontend/frontend/views.py
from datetime import datetime, timedelta, timezone

import jwt
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ViewDoesNotExist
from django.http import Http404, JsonResponse
from django.views import View
from django.views.generic.base import TemplateView
from ragb.settings import JWT_SECRET, LIGHTS, WEBSOCKET_ENDPOINT


def get_context_from_proj(kind, chans):
    print(kind, chans)
    match kind:
        case "blinder":
            return [
                {
                    "id": chans[i],
                    "position_y": ((15 - i) // 4) * 25 + 15,
                    "position_x": ((15 - i) % 4) * 25 + 15,
                }
                for i in range(len(chans))
            ]
        case "led_tub":
            return [
                {
                    "id": chans[i],
                    "position": i * 10,
                }
                for i in range(len(chans))
            ]
        case "spot":
            return {
                "id": chans[0],
            }

        case _:
            raise ViewDoesNotExist()


class TokenView(View, LoginRequiredMixin):
    def get(self, request, *arg, **kwargs):
        return JsonResponse(
            {
                "token": jwt.encode(
                    {
                        "exp": datetime.now(tz=timezone.utc) + timedelta(hours=9),
                        "sub": "ragb",
                        "user": self.request.user.username,
                        "scope": "modify",
                    },
                    JWT_SECRET,
                )
            }
        )


class LightView(TemplateView):
    def get_template_names(self):
        lights = LIGHTS["lights"][self.kwargs["light"]]
        return [f"frontend/{lights['kind']}.html"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["jwt"] = jwt.encode(
                {
                    "exp": datetime.now(tz=timezone.utc) + timedelta(hours=9),
                    "sub": "ragb",
                    "user": self.request.user.username,
                    "scope": "modify",
                },
                JWT_SECRET,
            )
        context["websocket_endpoint"] = WEBSOCKET_ENDPOINT
        light = self.kwargs["light"]
        if light not in LIGHTS["lights"]:
            raise Http404("Light does not exist")
        lights = LIGHTS["lights"][light]
        context["lights"] = get_context_from_proj(lights["kind"], lights["channels"])
        context["light_name"] = lights["name"]

        return context


class HomeView(TemplateView):
    template_name = "frontend/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["websocket_endpoint"] = WEBSOCKET_ENDPOINT
        lights = LIGHTS["lights"]
        context["lights"] = lights

        return context

ragbv2/frontend/frontend/templates/frontend/base.html
{% load static %}
<!doctype html>
<html data-theme="light" lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light dark" />
    <link rel="stylesheet" href="{% static "css/pico.pumpkin.min.css" %}">
    <title>R/AGB</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'media/logo.png' %}">
  </head>
  <body>
    <header class="container">
        <nav>
          <ul>
            <li>

        <a aria-label="Page d'accueil" href="{% url "frontend:home" %}">
          <img style="height:50px;" src="{% static "media/logo.png" %}" alt="Logo d'hackens"/>
        </a>
            </li>
          </ul>
          <ul>
            <li class="hide-before-sm">
              <a class="contrast" href="{% url "frontend:home" %}">Accueil</a>
            </li>
            <li class="hide-before-sm">
              <a class="contrast" href="/api-docs/">API</a>
            </li>
            {% if user.is_staff %}
            <li class="hide-before-sm">
              <a class="contrast" href="{% url "admin:index" %}">Admin</a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li>
              <a href="{% url "authens:logout" %}">
                <strong>Déconnexion</strong>
              </a>
            </li>
            <li>
              <button>
                🧑&nbsp;{{ user.username }}
              </button>
            </li>
            {% else %}
            <li>
              <a href="{% url "authens:login" %}">
                Connexion
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>
    </header>
    <main class="container">
      {% block content %}{% endblock %}
    </main>
  </body>
</html>

ragbv2/frontend/frontend/templates/frontend/blinder.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
{% if not user.is_authenticated %}
<article>
  <p>
  Connectez-vous pour pouvoir modifier des couleurs
  </p>
</article>
{% endif %}

<section>
  <h1>{{ light_name }}</h1>
  <figure>
    <svg viewBox="-3.5 -3.5 112 112" version="1.1" id="blinder" >
      <style>
        circle {
          fill: white;
          stroke: black;
          stroke-width: 2;
        }
        {% if user.is_authenticated %}
        circle:hover {
          stroke: grey;
        }
        {% endif %}
      </style>
      <g id="layer1">
        <rect style="fill:none;stroke:#000000;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:none" width="110" height="110" x="-2.5" y="-2.5" rx="15" />
        {% for light in lights %}
        <circle id="light{{ light.id }}" r="10" cx="{{ light.position_x }}" cy="{{ light.position_y }}" data-target="modal-light{{ light.id }}" class="modal-trigger"/>
        {% endfor %}
      </g>
    </svg>
  </figure>
</section>
{% if user.is_authenticated %}
{% for light in lights %}
<dialog id="modal-light{{light.id}}">
  <article>
    <header>
      <button class="close-modal" rel="prev" aria-label="close"></button>
      <h3>Couleur du pixel n°{{light.id}}</h3>
    </header>
    <section>
      <form>
        <input id="input-light{{light.id}}" class="input" type="color" name="light{{light.id}}">
        <button class="save-color" data-target="{{light.id}}">Enregistrer</button>
      </form>
    </section>
  </article>
</dialog>
{% endfor %}
{% endif %}
<dialog open id="modal-loading">
  <article aria-busy="true"></article>
</dialog>
<script>const WEBSOCKET_ENDPOINT = "{{ websocket_endpoint }}";</script>
{% if user.is_authenticated %}
<script>const JWT = "{{ jwt }}";</script>
{% endif %}
<script src="{% static "js/update-color.js" %}" defer></script>
{% endblock %}

ragbv2/frontend/frontend/templates/frontend/led_tub.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}

<section class="section content container is-max-desktop">
  <h1 class="title is-3">{{ object.name }}</h1>
  <svg viewBox="-1 -1 162 12" version="1.1" id="barreled" >
    <style>
      rect {
        fill: white;
        stroke: black;
        stroke-width: 1;
      }
      {% if user.is_authenticated %}
      rect:hover {
        stroke: grey;
      }
      {% endif %}
    </style>
    <g id="layer1">
      {% for light in lights %}
      <rect id="light{{ light.id }}" width="10" height="10" x="{{ light.position }}" y="0" class="modal-trigger" data-target="modal-light{{ light.id }}" />
      {% endfor %}
    </g>
  </svg>
</section>

{% if user.is_authenticated %}
{% for light in lights %}
<dialog id="modal-light{{light.id}}">
  <article>
    <header>
      <button class="close-modal" rel="prev" aria-label="close"></button>
      <h3>Couleur du pixel n°{{light.id}}</h3>
    </header>
    <section>
      <form>
        <input id="input-light{{light.id}}" class="input" type="color" name="light{{light.id}}">
        <button class="save-color" data-target="{{light.id}}">Enregistrer</button>
      </form>
    </section>
  </article>
</dialog>
{% endfor %}
{% endif %}
<dialog open id="modal-loading">
  <article aria-busy="true"></article>
</dialog>
<script>const WEBSOCKET_ENDPOINT = "{{ websocket_endpoint }}";</script>
{% if user.is_authenticated %}
<script>const JWT = "{{ jwt }}";</script>
{% endif %}
<script src="{% static "js/update-color.js" %}" defer></script>
{% endblock %}

ragbv2/frontend/frontend/templates/frontend/spot.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
{% if not user.is_authenticated %}
<article>
  <p>
  Connectez-vous pour pouvoir modifier des couleurs
  </p>
</article>
{% endif %}

<section>
  <h1>{{ light_name }}</h1>
    {% if user.is_authenticated %}
      <form>
        <input id="input-light{{lights.id}}" class="input" type="color" name="light{{lights.id}}">
        <button class="save-color" data-target="{{lights.id}}">Enregistrer</button>
      </form>
    {% endif %}
</section>
<dialog open id="modal-loading">
  <article aria-busy="true"></article>
</dialog>
<script>const WEBSOCKET_ENDPOINT = "{{ websocket_endpoint }}";</script>
{% if user.is_authenticated %}
<script>const JWT = "{{ jwt }}";</script>
{% endif %}
<script src="{% static "js/update-color.js" %}" defer></script>
{% endblock %}

ragbv2/frontend/frontend/templates/frontend/tradi.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
{% if not user.is_authenticated %}
<article>
  <p>
  Connectez-vous pour pouvoir modifier des couleurs
  </p>
</article>
{% endif %}

<section>
  <h1>{{ light_name }}</h1>
    {% if user.is_authenticated %}
      <form>
        <input id="input-light{{lights.id}}" class="input" type="color" name="light{{lights.id}}">
        <button class="save-color" data-target="{{lights.id}}">Enregistrer</button>
      </form>
    {% endif %}
</section>
<dialog open id="modal-loading">
  <article aria-busy="true"></article>
</dialog>
<script>const WEBSOCKET_ENDPOINT = "{{ websocket_endpoint }}";</script>
{% if user.is_authenticated %}
<script>const JWT = "{{ jwt }}";</script>
{% endif %}
<script src="{% static "js/update-color.js" %}" defer></script>
{% endblock %}